# Generated by Django 4.1 on 2022-08-24 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pollyhouse_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='village',
            old_name='village',
            new_name='district',
        ),
    ]
