# Generated by Django 4.1 on 2022-08-25 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pollyhouse_app', '0002_rename_village_village_district'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Avatar'),
        ),
        migrations.AddField(
            model_name='signup',
            name='pin',
            field=models.IntegerField(blank=True, null=True, verbose_name='Pin'),
        ),
    ]
