# Generated by Django 4.1 on 2022-08-25 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pollyhouse_app', '0003_signup_avatar_signup_pin'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='signup',
            options={'verbose_name_plural': 'Sign Up'},
        ),
    ]
