# Generated by Django 4.1 on 2022-08-26 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pollyhouse_app', '0006_remove_signup_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='avatar',
            field=models.ImageField(default=True, upload_to='', verbose_name='Avatar'),
        ),
    ]
