# Generated by Django 4.1 on 2022-08-26 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pollyhouse_app', '0007_signup_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signup',
            name='avatar',
        ),
    ]
