# Generated by Django 4.1 on 2022-08-27 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pollyhouse_app', '0009_signup_district_signup_state_signup_village'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='confirm_password',
            field=models.CharField(default=None, max_length=30, verbose_name='confirm Password'),
        ),
        migrations.AddField(
            model_name='signup',
            name='password',
            field=models.CharField(default=None, max_length=30, verbose_name='Password'),
        ),
    ]
