# Generated by Django 4.1 on 2022-08-27 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pollyhouse_app', '0010_signup_confirm_password_signup_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='village',
            name='district',
        ),
        migrations.AlterField(
            model_name='signup',
            name='address',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='signup',
            name='confirm_password',
            field=models.CharField(default=None, max_length=15),
        ),
        migrations.AlterField(
            model_name='signup',
            name='district',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='signup',
            name='name',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='signup',
            name='password',
            field=models.CharField(default=None, max_length=15),
        ),
        migrations.AlterField(
            model_name='signup',
            name='phone_number',
            field=models.CharField(default=None, max_length=10),
        ),
        migrations.AlterField(
            model_name='signup',
            name='state',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='signup',
            name='village',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.DeleteModel(
            name='District',
        ),
        migrations.DeleteModel(
            name='State',
        ),
        migrations.DeleteModel(
            name='Village',
        ),
    ]
